# Generated by Django 5.1.4 on 2025-01-07 18:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pin',
            field=models.CharField(default=1111, max_length=6, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.RegexValidator(message='PIN must be numeric and 4-6 digits long.', regex='^\\d{4,6}$')]),
            preserve_default=False,
        ),
    ]
