# Generated by Django 5.1.4 on 2025-01-07 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestApi', '0002_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
